In [2]:
import torch

In [3]:
torch.accelerator.is_available()

True

In [4]:
torch.accelerator.current_accelerator().type

'cuda'

In [6]:
tensor = torch.rand(1,3)

In [7]:
tensor

tensor([[0.0662, 0.3520, 0.6532]])

In [10]:
tensor[0]

tensor([0.0662, 0.3520, 0.6532])

In [11]:
tensor[0][1]

tensor(0.3520)

In [12]:
tensor2 = torch.rand(3)

In [13]:
tensor2

tensor([0.4357, 0.3548, 0.6529])